name = "PhD"
version = "0.1.0"
license = "MIT"
author = "Georgios Loukas"
maintainer = "georgios.a.loukas@gmail.com"
copyright = "Copyright 2026, iLouke"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["openblas"]

[dependencies]
stdlib          = "*"					                                            # Standard Modern Fortran Library
#openmp        = "*"						                                         # Multithread Capability
toml-f.git      = "https://github.com/toml-f/toml-f"                                # Reading simulation config files
pyplot-fortran  = { git="https://github.com/jacobwilliams/pyplot-fortran.git" }